### ISSUE TITLE
Custom tags instead of ^link^

### ISSUE THREAD

**Issue by jobindjohn** [gladed/linkist#1]
Is there an option to change the tag to something else (for e.g. [[ ]]), so that it is compatible with the system of links that I already use? Thanks!

**Comment by gladed** [comment]
Congrats on being issue #1 :)

There is not, but let's figure something out. What class of characters appear between `[[ ]]` such that linkist can recognize it as a link? `[0-9A-Z]` or something else?

Would you want to generate a tag of a different format also, e.g. `[[2020050708091234]]`? If you could post some examples it would help.

**Comment by jobindjohn** [comment]
Great! 

I have been using [Zettlr](https://github.com/Zettlr/Zettlr). It uses both types of tags you mentioned to make the links: characters `[0-9A-Z]` for file names and `[[2020050708091234]]` for time-based links. It would be nice to have something similar within Atom.

**Comment by gladed** [comment]
Try 1.3.3

**Comment by gladed** [comment]
Hey @jobindj just wanted to let you know I have moved this plugin to VSCode and changed its behavior a bit.

I haven't re-implemented this feature since I'm standardizing on `[description](^abcd^)` style for [reasons described here](https://github.com/gladed/linkist/wiki/FAQ#why-not-use-202006041255-or-my-link-name-style-identifiers-like-other-zettelkasten-systems). And there are other good vscode plugins for the `[[something-here]]` style.

I hope you're able to find a system that works for you!

**Comment by jobindjohn** [comment]
Thanks! That looks great!
